system:
  base_path: data
  log_level: INFO
  testing_mode: false
  max_disk_usage_pct: 85.0
camera:
  mock_mode: false
  preview_width: 640
  preview_height: 480
  preview_fps: 10
  still_width: 3840
  still_height: 2160
  still_quality: 90
  use_picamera2: true
motion:
  sensitivity: 25
  min_area: 500
  blur_size: 21
  dilate_iterations: 10
  history_frames: 50
  inactivity_timeout_sec: 10.0
  max_gif_frames: 20
  gif_fps: 4
  max_gif_width: 1920
environment:
  sensor_pin: 4
  poll_interval_sec: 60
  temp_low_threshold: 22.0
  temp_high_threshold: 33.0
  alert_cooldown_min: 15
relay:
  config_path: config/relay.yaml
  mock_mode: false
telegram:
  token_file: .env
  admin_chat_ids: []
storage:
  db_filename: turtlecam.db
  image_dir: images
  archive_dir: archive
  retention_days: 30
  auto_cleanup: true
time_sync:
  use_rtc: true
  rtc_module: DS3231
  ntp_server: pool.ntp.org
  sync_interval_hours: 24
